### ISSUE TITLE
Share content

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#112]
- [ ] add share button to content
- [ ] open modal with versioned and/or unversioned content link
- [ ] add copy to clipboard button(s)
- [ ] close modal

[Figma](https://www.figma.com/file/tAK0AcupI5t8B8NKwBflaq/%CE%94-networking-feature-share-content?node-id=87%3A486)

**Comment by psobrakseaton** [comment]
Here is the link to the Figma file for this task: [https://www.figma.com/file/tAK0AcupI5t8B8NKwBflaq/%CE%94-networking-feature-share-content?node-id=87%3A486](https://www.figma.com/file/tAK0AcupI5t8B8NKwBflaq/%CE%94-networking-feature-share-content?node-id=87%3A486)

For the sake of simplicity, the current design for the sharing of content will be very similar to sharing a profile. The same designs for the URL modals will be used, and the search/find button remains the same for whatever URL you are sharing.

The designs will deviate slightly from each other when we introduce bookmarking of profiles and bookmarking of content (next work cycle?).

There isn't yet any copy written for sharing the content URL but I will check the latest build and talk with James and put any changes for the copy here instead of the Figma.

Our discussions on Slack yesterday in regards to the copywriting for the modals went beyond what was reflected in the Figma, so use the Figma as the source of truth for visual design and the copy will be reflected here.
