### ISSUE TITLE
Add author(s)

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#166]
On the edit content screen, add the ability to add and remove authors from content.

- [x] add dropdown of all locally known profiles
- [x] add button to add author
- [x] display all currently added authors
- [x] for each, let author be removed

[Figma](https://www.figma.com/file/zTtZEFkwoZnMZjUJiC8VpH/%23166---Add-author(s))

**Comment by psobrakseaton** [comment]
Figma: [#166 - Add author(s)](https://www.figma.com/file/zTtZEFkwoZnMZjUJiC8VpH/166-Add-author-s?node-id=0%3A1)

**Comment by psobrakseaton** [comment]
[The Figma](https://www.figma.com/file/zTtZEFkwoZnMZjUJiC8VpH/166-Add-author-s?node-id=4%3A113) has been updated with the first iteration for adding authors and changing their order. Having a UI item for each authors position is not great, you'll have to follow them up and down the list with your mouse in order to change where they are. The sooner we can add drag n drop positioning the better.

The key design takeaways are:
- Added an "Authors" section to the the form.
- Added a dropdown for selecting from a list of followed profiles.
- Added up and down arrows to change the order.
- A user cannot currently delete themselves as an author, so there is no X by their name.
- The top and bottom positions on the chart have their corresponding arrows disabled if they cannot move in that direction.
- On the content list, there is currently no designs or behavior to limit the number of authors displayed on the content screen. This is intentional for now since displaying participants is such an important feature. Designing some sort of abbreviation for when we have say, 10+ authors is currently out of scope for this task.

**Comment by jameslibscie** [comment]
I like it! Have a couple of suggestions:
1. I think Authors should be below Description or perhaps above Title as conceptually the Title and Description belong together imo. This does differ from the display order, so I don't feel too strongly about this.
2. I think the dropdown text should read something like "Add author" - or even better - "Add nth author"
3. I don't think there is an introductory text necessary above the dropdown

Overall, I think this page looks nicer. The smaller content type list helps and I really think we should implement this when we expand the content types (part of this cycle!)
I also like the main file / supporting files split, but I guess that's out of scope otherwise - maybe for later.

**Comment by psobrakseaton** [comment]
> I like it! Have a couple of suggestions:
> 
> 1. I think Authors should be below Description or perhaps above Title as conceptually the Title and Description belong together imo. This does differ from the display order, so I don't feel too strongly about this.
> 2. I think the dropdown text should read something like "Add author" - or even better - "Add nth author"
> 3. I don't think there is an introductory text necessary above the dropdown
> 
> Overall, I think this page looks nicer. The smaller content type list helps and I really think we should implement this when we expand the content types (part of this cycle!)
> I also like the main file / supporting files split, but I guess that's out of scope otherwise - maybe for later.

Thanks James! I think you're right about 2 and 3. I will put that into effect now. I don't agree with 1 and I think we should keep the display order for now.

Yeah, I really like the main/supporting file split, but unfortunately that will have to wait until later for implementation.

**Comment by chartgerink** [comment]
@psobrakseaton if we're keeping the order, might it be worth suggesting to have it be 1:1 with the content screen? That is:

* Content type
* Title
* Authors
* Description
* Main file
* Supporting files

Not super important, but a thought 😊

**Comment by jameslibscie** [comment]
@chartgerink The reason why I proposed the current order initially is because people will have to get used to working as-you-go and certain decisions would help to inform the next. Content type is the most defining, but also the file selection is a moment that people really have to stop and think. This in turn may influence the content type selection, but especially the title and description. The order is kinda weird as it is now, but there's a reason why it is this way :)
