### ISSUE TITLE
View parents context for a content module (mini-mapping)

### ISSUE THREAD

**Issue by juliangruber** [hypergraph-xyz/desktop#169]
Show a specific minimapping icon depending on the number of parent modules.

[Figma](https://www.figma.com/file/FM8tovSvzNVCKqqOKdseaq/%23169---View-parents-context-for-a-content-module-(mini-mapping)) | Review @chartgerink @psobrakseaton

**Comment by psobrakseaton** [comment]
Figma: [#169 - View parents context for a content module (mini-mapping)](https://www.figma.com/file/FM8tovSvzNVCKqqOKdseaq/169-View-parents-context-for-a-content-module-mini-mapping?node-id=0%3A1)

**Comment by chartgerink** [comment]
If we make the minimap clickable, we could think about removing the "Follows from" dropdown? 

I can imagine clicking the minimap displays the parent content module directly if there's 1 parent, and displays a list of parent content modules if there are >1. This would permit for scaling of viewing an "unlimited" amount of parents and tackle with parents of parents of parents :')

In essence, this would be like a parent feed window. What do you think?

**Comment by jameslibscie** [comment]
> If we make the minimap clickable, we could think about removing the "Follows from" dropdown?
> 
> I can imagine clicking the minimap displays the parent content module directly if there's 1 parent, and displays a list of parent content modules if there are >1. This would permit for scaling of viewing an "unlimited" amount of parents and tackle with parents of parents of parents :')
> 
> In essence, this would be like a parent feed window. What do you think?

I'd be for something like this, but if it introduces much extra design work, it might be wise to implement it as the next iteration of this feature.

**Comment by chartgerink** [comment]
This would not require any additional designs, only code AFAIK? I also realised we don't have multi-parents support so we can limit it to opening the parent content only for now :)

**Comment by psobrakseaton** [comment]
The Figma has now been updated to the latest working designs.

The design extends a bit beyond current capability in terms of the numbers of parents that can be represented in the minimap (up to 4+ parents), so for now we will pretty much only have single parent icons, but the others are there for good measure.

The icon and the icon-area have a unique size so they are measured accordingly in the guidelines examples. @chartgerink  and I discussed colors and the meanings behind color choices and we settled upon a "heat map" of sorts with the colors warming as it connects to more and more parents.

When the icon is clicked it should open the "Follows from" dropdown as though the caret had been clicked.

On a side note, I think we should add a redesign of the "Follows from" dropdown sometime in the near future. There are some pretty obvious weaknesses with the current design. @jameslibscie 

As a final bonus, here's a pretty photo of how the icons look in light mode 😍

![light-test](https://user-images.githubusercontent.com/28573875/88812532-1c777580-d1b8-11ea-9c16-ed3796cddba0.png)

**Comment by psobrakseaton** [comment]
I'm going to start posting some reference images in the issues here so that @chartgerink can find marketing images directly through issues.

![icons](https://user-images.githubusercontent.com/28573875/88813937-cf949e80-d1b9-11ea-9bb2-7f7ee501df1b.png)
![4plus-parents-guides](https://user-images.githubusercontent.com/28573875/88813969-d3c0bc00-d1b9-11ea-94a1-09d9ac3af798.png)
![no-parent-guide](https://user-images.githubusercontent.com/28573875/88813974-d58a7f80-d1b9-11ea-92f5-048df8f5e927.png)

**Comment by jameslibscie** [comment]
Nice! I have some questions:
1. What does the + mean? Does it mean "more than 4"? I could imagine this being confused with the + that means "add".
2. Does this have a hover state? Or a tooltip?
3. What happens when you click the big hex? What happens when you click and there are no parents? What happens when you click and there are multiple parents?
4. Does this only show direct parents or also parents of parents?
5. Does this icon also show on the content page?

**Comment by chartgerink** [comment]
AFAIK:

1. `+` is >3. We used ellipses (`...`) as well, but it was too small. What would be an alternative to this? 
2. Not at the moment. Would work well in a tour the first time it shows?
3. The interaction is on the whole image, not specific parts. When there are no parents, it wouldn't do anything. Multi-parents is indeed a good point, which is why I suggested earlier to include a "Parent feed" that would solve this issue. Note: We cannot yet assign multiple parents so that is not a direct issue.
4. Only direct parents. Parents of parents is out of scope for now.
5. Good point! We didn't discuss; it is implied it shows on all complete content cards based on metadata? (i.e., the ones in the Feed, Drafts, and Profile)

![](https://media.giphy.com/media/Izp9YI41gRcxCOeqyd/giphy.gif)

**Comment by jameslibscie** [comment]
Maybe it could show the total number of parents? Or it could be a hex but the left edge of the "cable" could be zigzagged off to suggest there is more to the left of it. Either way, seeing as we're only implementing 1 parent in Hypergraph, I'd say the current design can stand and we can revisit when we implement multiple parents if something comes out of a test.

**Comment by juliangruber** [comment]
This is nice work!

If we don't add a hover state, and clicking a zero-parents icon doesn't do anything, while clicking a one-or-more-parents icon does, the information whether it is clickable is encoded too complex. Imagine, how would people learn whether this icon is clickable? Say they see an icon with zero parents first, try to click it and nothing happens, wouldn't they assume this icon isn't clickable no matter what?

**Comment by psobrakseaton** [comment]
> This is nice work!
> 
> If we don't add a hover state, and clicking a zero-parents icon doesn't do anything, while clicking a one-or-more-parents icon does, the information whether it is clickable is encoded too complex. Imagine, how would people learn whether this icon is clickable? Say they see an icon with zero parents first, try to click it and nothing happens, wouldn't they assume this icon isn't clickable no matter what?

I completely agree with this...I can a potential solution:

Ditch the "no-paraents" icon entirely and only start mapping it when there is something to follow from. That would make the icon more enticing to click upon and would remove this awkward null state.

As for @jameslibscie questions, I think @chartgerink answered these perfectly. A lot of the functionality is currently out of scope or not doable at the moment. These current designs allow for some of the growth that will occur, but can later be transferred to linking to a connection page instead of a "follows from" list.

**Comment by jameslibscie** [comment]
+1 on ditching the icon when there are no parents
And +1 for the rest too really :) Sounds good!

**Comment by jameslibscie** [comment]
So this is turning out to be quite a complicated issue as so many things come together here. I've chatted with @psobrakseaton and have a proposal that allows us to take the first step now, simplify the current app and prepare us for future iterations. With a bit of luck, we might have time before release for steps 2 or 3, but it's OK if we don't.

**Step 1: Implement mini-map icon for parents-only (= this issue)**

- Display mini-map icon in all content lists when content has 1 or more parents
- Replace parents link with mini-map icon on content page when content has 1 or more parents <- needs design
- Hover on "pipe" to view tooltip info about parent <- needs design
- Click on "pipe" to open content page for parent
- Remove follows-from accordion altogether

This would give us a more visual way of presenting the connection to parents, while ditching duplicate features that might be confusing. Although it's less easy to view multiple steps back in 1 go, it is still possible to trace this history. This also allows us to move more towards a multiple parent implementation, as detailed in the following steps.

**Step 2 or 3: Implement mini-map icon for children**

- Add children "pipes" to the icon with the same interactions as for parents

This makes for easier navigation "up and down" and provides more context for each piece of content.

**Step 2 or 3: Implement multiple parents**

- Expand "add/edit content" page with multiple parent selector, using same design pattern as for multiple author selector

Because we've removed the other features, implementing multiple parents becomes easy. Also, there is no waste due to developing intermediate designs (like threading) that might not work in a multiple-parent context.

**Step 4: Full mapping**

Now we can start to think about something like an "expand" button on the mini map that creates a full map with multiple levels of connectivity - to fully show the network.

**Comment by chartgerink** [comment]
Thanks @jameslibscie!

How about we do system tooltips for now, just like with the network status indicator #168? I really like the idea of hovering and clicking on each "pipe" separately to drive towards the parent. @juliangruber do you have any comments regarding implementability --- can we tag these URLs to the separate parts of the SVG without much issue or do you feel there might be issues there?

@psobrakseaton and I had a meeting about the way parent "pipes" could look like in the content screen (beyond the content card where the minimap lives). We'll share some initial ideas around those designs later today.

Step 2 and beyond are indeed good pointers for next cycles :) We took these in to account for the designs that are following.

**Comment by psobrakseaton** [comment]
Here are some quick exports of our exploratory designs. The basic idea is to provide a visually strong way to represent parents and children on the content screens.

Mixed sources
![ribbon-flow](https://user-images.githubusercontent.com/28573875/89387087-496ce080-d702-11ea-9ae5-ecb06755a4af.png)

Less messy, sorted groups
![ribbon-flow-sorted](https://user-images.githubusercontent.com/28573875/89387091-4a9e0d80-d702-11ea-8e75-a229858d8378.png)

Just thought I'd leave this here as well since this was some of the things we thought it was reminiscent of when making it haha
<img width="724" alt="Screen Shot 2020-08-05 at 09 59 47" src="https://user-images.githubusercontent.com/28573875/89387172-686b7280-d702-11ea-9d34-0cfb40afece0.png">

We still have stuff to talk about in regards to specific task and success measures for this cycle in particular. But we wanted to post this for feedback anyways.

**Comment by juliangruber** [comment]
> @juliangruber do you have any comments regarding implementability --- can we tag these URLs to the separate parts of the SVG without much issue or do you feel there might be issues there?

This is possible, but more work for sure. I'd label this task alone as a day's work.

**Comment by psobrakseaton** [comment]
> > @juliangruber do you have any comments regarding implementability --- can we tag these URLs to the separate parts of the SVG without much issue or do you feel there might be issues there?
> 
> This is possible, but more work for sure. I'd label this task alone as a day's work.

Yeah, a day's work seems really out of scope at this time...

**Comment by jameslibscie** [comment]
Because we're only implementing 1 parent atm, we could scope it so it's an on-off thing and the entire icon is clickable / hoverable if displayed. If there are multiple parents somehow, it still displays the icon with 1 pipe and clicking it takes you to the first parent?

**Comment by jameslibscie** [comment]
This pushes back the work on splitting the SVG to when we do the multiple parents and/or display children issues.

**Comment by jameslibscie** [comment]
@psobrakseaton @chartgerink The design looks cool, but I do wonder whether having multiple interfaces for the same thing is wise. I think at least for now we should implement the mini-map icon in both places and progress to new designs later.

**Comment by chartgerink** [comment]
> @psobrakseaton @chartgerink The design looks cool, but I do wonder whether having multiple interfaces for the same thing is wise. I think at least for now we should implement the mini-map icon in both places and progress to new designs later.

I'm confused, you said it needed designs? The minimap is built for the content card and dropping it 1:1 in the content screen doesn't really work given that the negative space layout is so different. For example, a logical place would be top left but that means shifting everything in the content screen as well, so it has cascading effects on the design. I do agree consistency of designs will help learning and having discordant designs won't help for that.

![Screenshot 2020-08-05 at 13 55 31](https://user-images.githubusercontent.com/2946344/89410070-5817bf80-d723-11ea-9db0-72e3c454a21b.png)

The SVG splitting was never set for this cycle so it doesn't push back anything, AFAIK.

**Comment by jameslibscie** [comment]
Ah, was it not possible to find a fitting place for the icon on the content page? I was already a little worried that the placement might be difficult. After looking at the above screenshot a couple of times with the icon top-left, I must say I'm warming to it, but once children are added it's probably going to get too big.

**Comment by chartgerink** [comment]
I'll defer to @psobrakseaton for design decisions. What I posted was a simple mockup to indicate it has cascading effects and is not a design proposal.

**Comment by psobrakseaton** [comment]
Ok, so after gaming out a lot of possibilities with @chartgerink, I think we've hit upon the best (but still imperfect) solution to the questions of mini-mapping.

1. The "Follows from" dropdown will be eliminated and we will only have the mini-map (in it's currently designed form). The dropdown indicates children instead of parents, so we want to avoid that behavior with parents if we can.

2. Clicking on the mini map will take you to a follows-from/parents feed. This will be exactly like the other feeds we have (followed feeds and drafts), but will consist only of the parents of that content module. These parents can also have parents and this will also be indicated by mini-maps.

3. The content screens will have an indicator to show their current parental status (1, 2 ,3, +), the action will be the same as clicking on the mini-map, but their designs are still unknown.

I understand that this type of action has the potential to get the user pretty lost pretty quickly (going from a parent feed, to a parent feed of a parent feed, etc.), but I think that will be simplified by the introduction of breadcrumbs (next cycle hopefully), and this confusion will then ultimately be eliminated when the mini-map can finally lead to an actual visual map.

The biggest issue we are dealing with is the fact that we have two major things working against us, namely, the current lack of multiple parents and the lack of children. 

As I said in the beginning, I believe this is the most efficient and best solution given our current limitations. I will continue to work on the Figma today and get final designs and prototypes ready for tomorrow.

**Comment by jameslibscie** [comment]
Sounds great @psobrakseaton and @chartgerink!

**Comment by psobrakseaton** [comment]
Once more unto the breach, dear friends...

The Figma has been updated to the latest designs. Here is a quick summary of the changes:
- Clicking the mini-map will take you to a feed that showcases the parents of the content. If there is only one parent, it will still take you to a feed and not to the item directly.
- There is now a "Follows from..." icon button on content pages that have parents and they have the same interaction as if you clicked on the mini-map.
- The browser-like navigation is staying for now, and the follows-from-feeds now have a back arrow so you can briefly check parents and then return.

Here are some notes about potential questions that may arise:
- The "Follows from..." icon button may be hidden if there are a lot of files on the page, but I think that is the most logical place for it to be after some trial and error. I figure you will be exploring through content and moving next from the bottom works well.
- The mini-map is missing a hover state currently. I experimented with a few of them and nothing was quite right. I thought maybe it would be better to have an imperfect, but I have some upcoming plans about hover states, buttons, and colors that will address this and so I opted for no hover state yet as opposed to a half-implementation.
- The browser-like navigation is not good, but that also will be addressed (hopefully next cycle) with breadcrumbs. For now, the icon is a standard one we use and it is in a standard place and that is Good Enough For Now™.

Let me know if anything is unclear and I can always hop on a call and do a walkthrough.

**Comment by jameslibscie** [comment]
I think this will work :) Wondering whether it shouldn't be at the top of the page where the parent previously was, but I guess you've tried that

**Comment by psobrakseaton** [comment]
Yeah, that was @chartgerink's reaction as well to the placement originally, but when I tried it it felt like it was saying that the content below was what was following as opposed to "Here is Content X, here is its title, author, description, files, and here is what it follows from."

**Comment by psobrakseaton** [comment]
Summary of the post-meeting decision regarding the mini-mapping:

We will implement the icon only (already done in the first iteration of this task) and we will remove the click event (ie the opening of the "follows from..." dropdown). The icon should have some sort of explanatory text on hover,  so please @chartgerink and @jameslibscie propose what you think should be there. Something like "This item follows from 1 or more items" or something.

**Comment by chartgerink** [comment]
@jameslibscie what do you think of keeping the copy simple and having this hover? 

> Follows from <X>

**Comment by jameslibscie** [comment]
My preference would be "Follows from:", followed by a list of all the parents.

**Comment by chartgerink** [comment]
If that works in a system hover, I could be down with that. Might become massive though :)
