### ISSUE TITLE
Prettier forms

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#47]
Currently, the forms (on Windows?) aren't completely consistent style-wise. It is possible to fix this with CSS adjustments.

- [x] Dropdown styling (borders, padding, fonts, letter spacing)

**Proposed solution**
See also #16 for screenshots ([mock-up](https://github.com/hypergraph-xyz/desktop/issues/16#issuecomment-601738282), [current](https://github.com/hypergraph-xyz/desktop/issues/16#issuecomment-601741528))

**Comment by juliangruber** [comment]
> * Long file names currently run up to / over the 'X' icon - should be faded out

@psobrakseaton is working on a design for this

**Comment by psobrakseaton** [comment]
After a bit of thought and some discussion with Julian, we have opted to use an ellipses instead of fading out. The reason being that in the future the best way to handle this would be to do what they do in the finder where they have an ellipses between the long name and the file extension. With the fade out we don't have an elegant way of maintaining file extension visibility.

**Current Solution:** If the file name is too long add an ellipses (lorem-ipsum-doler...)

**Proposal Solution:** If the file name is too long add an ellipses before the last few characters (perhaps 5 characters that will shrink to 1 should the window collapse that far) and the extension (lorem-ipsum-doler...met-5.html)

@chartgerink, I wanted to tag you to see if you had any insight, but also so you can see how I am are handling currents/proposals.

**Comment by jameslibscie** [comment]
@psobrakseaton Sounds like a great solution!

**Comment by juliangruber** [comment]
Can we move the file names to a new issue? That doesn't have anything to do with forms

**Comment by jameslibscie** [comment]
> Can we move the file names to a new issue? That doesn't have anything to do with forms

Done! Split off into #56 . Is this ready for review now?

**Comment by juliangruber** [comment]
@jameslibscie thanks! both requests are implemented now. I didn't ask for review because you didn't add it to this issue's process, and on my machine it looks as close as it can get at the moment. Do you want to take another look? It's in #master now.

**Comment by jameslibscie** [comment]
Great! I'll take a look at it now. I think I haven't communicated my idea regarding the workflow properly. For now, assume review on all the issues I create (even if it's stupid small stuff) and we can discuss this further in the retrospective that will be planned early next week (this will come up in the dev meeting later).

**Comment by juliangruber** [comment]
Ok, this was confusing then...will we remove the `- [ ] Review` checkbox from all issues then, if it's implied?

**Comment by jameslibscie** [comment]
> Ok, this was confusing then...will we remove the `- [ ] Review` checkbox from all issues then, if it's implied?

I haven't added the workflow part to newer issues actually and have now removed it from the other open issues. Either an issue starts on `design` and then proceeds to `code`, or it starts on `code`, or it is a `task`.

**Comment by jameslibscie** [comment]
Looks great!
