### ISSUE TITLE
Scrolldown of header bar issue

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#86]
When I have more content than the profile screen can display at once, I scroll down and get the following visual bug

<img width="1552" alt="Screenshot 2020-05-26 at 10 29 05" src="https://user-images.githubusercontent.com/2946344/82882149-fbd53a00-9f40-11ea-8927-e735301f7429.png">

I was running Hypergraph 0.2.0 on the latest macOS Catalina.

**Comment by jameslibscie** [comment]
This also happens with me on Windows

**Comment by juliangruber** [comment]
@psobrakseaton there's a conflict between the sticky scrolling and the `<form>` element that we need for profile editing. Basically they're not compatible, we can have either or.

I demonstrated the problem in this video: https://youtu.be/ygJTtirJ6oc.

1) You see scrolling on the profile page, which has been fixed, because I removed the `<form>` element from this
2) Once edit mode is enabled, scrolling breaks. There's no straight forward way to fix it, and it doesn't make sense to scroll away what you're editing either.
3) Black screen while I change the code
4) A proposed fix is to remove the content from the profile screen while editing, which will prevent scrolling in the first place. We might want to add more content to this edit screen in the future.

What do you think?
